development:
  adapter: postgresql
  encoding: unicode
  database: tecece_development
  pool: 5
  username: postgres
  password: postgres
  reconnect: true

test:
  adapter: postgresql
  encoding: unicode
  database: tecece_test
  pool: 5
  username: postgres
  password: postgres
  reconnect: true

production:
  adapter: postgresql
  encoding: unicode
  database: tecece_production
  pool: 5
  username: postgres
  reconnect: true
